global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'node1'
    static_configs:
      - targets: ['192.168.111.136:9100']
rule_files:
  - "/etc/prometheus/node2_alerts.yml"
 
